version: '3.8'
services:
  jenkins:
    build:
      dockerfile: Dockerfile
      context: .
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
    - /home/ubuntu/jenkins_in_docker/jenkins_configuration:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock